name: cte
version: 0.6.1
synopsis: Utility functions for working with CTE — Common Equiform Time.
category: Time
homepage: https://galen.xyz/cte/
maintainer: Galen Huntington
license: MIT

defaults: galenhuntington/hpack-defaults@27874600a9673795a129b2f7523451793a39aaf4

source-dirs:
- .

default-extensions:
- OverloadedStrings

library: {}

executables:
  # still keeping this old thing
  gdate:
    main: gdate.hs

flags:
  linear:
    description: Depend on linear package, to make its instances available; also adds orphan instances.  Since exports conflict with vector-space, none of the operators will be re-exported.
    default: false
    manual: true
  torsor:
    description: Include torsor dependency and instances (one orphan instance needed).
    default: false
    manual: true

when:
- condition: flag(linear)
  dependencies:
    - linear
- condition: flag(torsor)
  dependencies:
    - torsor

dependencies:
- base
- base-prelude
- extended-reals
- time
- clock
- optparse-applicative
- vector-space
# - QuickCheck

